apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keh-address-book-lambda
  description: Weekly AWS Lambda that retrieves ONS Digital GitHub usernames and verified email addresses for the Digital Landscape address book.
  annotations:
    github.com/project-slug: ONS-Innovation/keh-address-book-lambda
  links:
    - url: https://ons-innovation.github.io/keh-address-book-lambda
      title: Address Book Lambda Documentation
spec:
  type: service
  lifecycle: production
  owner: keh-dev
